version: '3'

services:
  postgres:
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - online-store

  online-store:
    build: .
    ports:
      - 9090:9090
    networks:
      - online-store
    env_file:
      - .env
    depends_on:
      - postgres


networks:
  online-store:
